### ISSUE TITLE
Hot reload fails with rsync server greeting

### ISSUE THREAD

**Issue by elliott-davis** [garden-io/garden#1033]
### Current Behavior

When starting a service with hot reload (after making sure all other services where deleted) I get the following error when saving a file in the project:

```Failed hot-reloading service canoe. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command failed: rsync -vrpztgo /Users/elliott.davis/src/.../app/ rsync://localhost:60706/volume/app/app/
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1677) [sender=3.1.3]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Expected behavior

I expect the reload to work for my application and not get an rsync error

### Reproducible example

```
garden dev --hot service1
<Crtl+C>
garden dev --hot service1
touch some_watched_file.txt
```

### Workaround

none found

### Suggested solution(s)

Ensure the syncing container restarts on failure

### Additional context

In some cases I see this happen even after deleting the namespace created by garden.

### Your environment

`garden version - 0.10.2`

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

EDIT: After enabling some more verbose logging I seem to get to this line https://github.com/garden-io/garden/blob/ff60e58be55cc28b280667aebd271c7fbb4ee51b/garden-service/src/plugins/kubernetes/status/status.ts#L366 where i get a massive k8s diff output showing deletions of all the rsync resources.

**Comment by elliott-davis** [comment]
Just to add on to this, I can also reproduce by:
```
garden dev --hot service1
// edit garden.yml
// save new file
// rsync error
```

which caused this output in the logs:

```user with uid 0 already exist and its root
/entrypoint.sh: ignoring /docker-entrypoint.d/*
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2019-07-25 23:53:28,514 CRIT Supervisor running as root (no user in config file)
2019-07-25 23:53:28,514 WARN Included extra file "/etc/supervisor.conf.d/supervisor.daemon.conf" during parsing
2019-07-25 23:53:28,523 INFO RPC interface 'supervisor' initialized
2019-07-25 23:53:28,524 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-07-25 23:53:28,524 INFO supervisord started with pid 1
2019-07-25 23:53:29,527 INFO spawned: 'rsync' with pid 20
2019-07-25 23:53:30,533 INFO success: rsync entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[1] Puma starting in cluster mode...
[1] * Version 4.0.1 (ruby 2.4.5-p335), codename: 4 Fast 4 Furious
[1] * Min threads: 5, max threads: 5
[1] * Environment: development
[1] * Process workers: 1
[1] * Preloading application
[1] * Listening on tcp://0.0.0.0:4000
[1] Use Ctrl-C to stop
[1] - Worker 0 (pid: 28) booted, phase: 0
2019-07-25 23:59:46,110 WARN received SIGTERM indicating exit request
[1] - Gracefully shutting down workers...
2019-07-25 23:59:46,112 INFO waiting for rsync to die
2019-07-25 23:59:46,511 INFO stopped: rsync (exit status 0)
```

After that, the 2nd container in the hot loaded services pod never came back

**Comment by eysi09** [comment]
Hi @elliott-davis :wave:

Are you by any chance using the edge release from our Github releases page? We merged some bug fixes for hot reload on Windows earlier today (although they shouldn’t have caused any regressions).

**Comment by elliott-davis** [comment]
Hi @eysi09 👋 

No, I'm still using the latest non-edge version 0.10.2. I'm happy to test out edge to see if I still have the issue.

**Comment by eysi09** [comment]
I've found a way to consistently reproduce this:

1. `garden deploy --hot node-service` (`hot-reload` example)
2. Edit `hot-reload/frontend` to trigger a hot reload
3. Change top level `garden.yml`. This will trigger a re-build and a re-deploy of the service since we changed it in step 2.
4. Edit `hot-reload/frontend` again to trigger another hot reload

Might be that Garden isn't picking up the `--hot` flag on that re-deploy and therefore the side car container is missing.

**Comment by edvald** [comment]
I have a suspicion. If we re-deploy the service after the config change, the tunnel that we previously created basically doesn't work anymore. We should either terminate the open tunnels on re-deploy, or (perhaps more robust and easier) add error handling and delete/recreate the tunnel when we run into this error.

**Comment by elliott-davis** [comment]
In my case, there is a sidecar in the hot reload containers pod but on
reload that sidecar dies and never comes back. I'll work on getting a repro
repo up this morning. It might be worth mentioning that I have both the
project and module yaml in the same garden file

**Comment by khaled** [comment]
i just saw this same issue occur under similar circumstances - i edited some tasks in a service's garden.yaml, after which the service redeployed.  then i made some code changes, and hot reload failed:

```
[2019-09-24T16:01:14.969Z] Error: Unexpected error while synchronising to service backend: Command failed with exit code 5 (EIO): rsync -vrpztgo /Users/kagrama/dev/xxx/yyy/sdm/backend/ rsync://localhost:65502/volume/app/
    at /snapshot/dist/build/src/plugins/kubernetes/hot-reload.js:0
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/dist/build/src/plugins/kubernetes/hot-reload.js:0)
Error Details:
error:
  command: >-
    rsync -vrpztgo /Users/kagrama/dev/xxx/yyy/sdm/backend/
    rsync://localhost:65502/volume/app/
  exitCode: 5
  exitCodeName: EIO
  stdout: ''
  stderr: >-
    rsync: did not see server greeting

    rsync error: error starting client-server protocol (code 5) at main.c(1677)
    [sender=3.1.3]
  all: >-
    rsync: did not see server greeting

    rsync error: error starting client-server protocol (code 5) at main.c(1677)
    [sender=3.1.3]
  failed: true
  timedOut: false
  isCanceled: false
  killed: false
serviceName: backend

**Comment by normanzb** [comment]
I can still reproduce this issue with 0.10.14, which i believe is latest version.
I have a helm module and a container module, helm module relies on container module for building the image to be deployed.
and inside container module, there are hot reload configured:
```
hotReload:
  sync:
  - source: services/backend/
    target: /opt/service/
  - source: services/frontend/
    target: /opt/frontend/
  postSyncCommand: [cd, /opt/frontend/, "&&", npm, run, build, "&&", cp, -r, /opt/frontend/build/, /opt/static/]
```
if I do `garden dev --hot=*` which includes the container module, the rsync always failed with exact same error as original post.

but if i do `garden dev --hot helm-module` somehow it works...
