### ISSUE TITLE
Include filename when we have invalid scheme in garden.yml

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#410]
### Current Behavior

When a user makes a mistake in a `garden.yml` file with invalid syntax we don't show which file contains the error.

```
link module 🔗

Error validating module user: key "servicePort" is not allowed at path .services[0][ports][0][servicePort], key .services[0][ports] does not contain 1 required value(s)
module:

See error.log for detailed error message
```

### Expected behavior

We should include which file could not be correctly parsed. 

### Your environment

```
garden -v
0.8.0
```

**Comment by drubin** [comment]
@thsig  I am not sure how easy it is to include the filename since I think that type of parsing happens higher up the chain, but even just the module/project would be an amazing improvement to knowing which file is invalid.

**Comment by thsig** [comment]
Hadn't started on this, but config-related error messages do seem to include the path to the failing file on `master`. Looks like this was fixed since 0.8.

**Comment by drubin** [comment]
@thsig The issue includes which version number this happens in. So it wasn't fixed in `0.8.0` 

Adding an invalid key ie `foo: bar` to a config in a module results in the following output on latest code

```
garden dev

Good morning! Let's get your environment wired up...

✔ local-kubernetes          → Configured
    ✔ ingress-controller        → Preparing chart... → Done (took 0.9 sec)
    ✔ kubernetes-dashboard      → Preparing chart... → Done (took 0.8 sec)
    ✔ default-backend           → Deploying version f4da12648f... → Done (took 4.5 sec)
    ✔ kubernetes-dashboard      → Deploying version f4da12648f... → Done (took 5.8 sec)
    ✔ ingress-controller        → Deploying version f4da12648f... → Done (took 21.7 sec)
✔ openfaas                  → Configured
    ✔ system                    → Preparing chart... → Done (took 1.2 sec)
    ✔ system                    → Deploying version f4da12648f... → Done (took 22.3 sec)

Error validating module hello-container: key "foo" is not allowed at path [foo]

See error.log for detailed error message
```

Same thing with `garden validate`

We don't link to the file. I am going to reopen this.
